### ISSUE TITLE
Thank You For The Repo, I need it!

### ISSUE THREAD

**Issue by HackYardo** [yashwanthSRIVAT/Acode-Termux#1]
I have `termux`, `ubuntu for termux` and `acode` on my phone, I can run code in termux.ubuntu and edit code in android.acode, but I **can not** run and edit the same one code file... Look for this repo to complete!

**Comment by yashwanthSRIVAT** [comment]
Hello! Glad my repo helped you! Are you asking to add like a hot-reload feature to this? Please DM me via Twitter (you can find on my GitHub profile) about your issue, so that we can help each other out!

**Comment by HackYardo** [comment]
I'm at a point on the planet where Google is disabled, so Twitter doesn't work.
But fortunately, **the issue has been solved.** Once I didn't **keep both programs(termux.ubuntu and acode) running**, so the files would disappear after editing.
